# Generated by Django 5.2.3 on 2025-06-12 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=255)),
                ('profession', models.CharField(unique=False)),
                ('address_street', models.CharField(blank=True, max_length=100, null=True)),
                ('address_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('address_state', models.CharField(blank=True, max_length=30, null=True)),
                ('address_zip', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('health_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core_api.healthprofessional')),
            ],
        ),
    ]
